flaskblog/main/routes.py
from flask import render_template, request, Blueprint, url_for
from flaskblog.models import Post
from flaskblog.posts.routes import view_blog

main = Blueprint('main', __name__)



@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
    vector1 = url_for('static', filename='profile_pics/vector1.jpg')
    vector2 = url_for('static', filename='profile_pics/vector2.png')
    vector3 = url_for('static', filename='profile_pics/vector3.png')
    return render_template('home.html', posts = posts, vector1=vector1, vector2=vector2, vector3=vector3)



@main.route("/about")
def about():
    profle_pic = url_for('static', filename='profile_pics/Profile.jpg')
    return render_template('about.html', title='About', profle_pic=profle_pic)


@main.route("/search", methods=('GET', 'POST'))
def search():
    if request.method == 'POST':
        search = request.form['search']
        search_data = Post.query.filter_by(title=search).first_or_404()
        
        return render_template('view_blog.html', post=search_data)

flaskblog/posts/routes.py
import base64
import os
from flask import (app, render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import NewBlogForm, UpdateBlogForm
from flaskblog.posts.utils import convertToBinaryData
from werkzeug.utils import secure_filename

posts = Blueprint('posts', __name__)

@posts.route("/new/blogpost",methods=('GET', 'POST'))
@login_required
def new_blog_post():
    form = NewBlogForm()

    if form.blog_image.data:
        file = request.files[form.blog_image.name]
        filename = secure_filename(file.filename)
        file_path = str('/static/blog_images/'+filename)
        file.save(os.path.join('flaskblog\\static\\blog_images', filename))

    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, blog_image=file_path)
        db.session.add(post)
        db.session.commit()
        flash(f'Your blog has been posted successfully!', 'success')
        return redirect(url_for('main.home'))
        
    return render_template('new_blog_post.html', title='New Post', form=form)




@posts.route("/viewblog/<int:post_id>",methods=('GET', 'POST'))
def view_blog(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('view_blog.html', title=post.title, post=post)



@posts.route("/viewblog/update/<int:post_id>",methods=['GET', 'POST'])
@login_required
def update_blog(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = UpdateBlogForm()

    if form.blog_image.data:
        file = request.files[form.blog_image.name]
        filename = secure_filename(file.filename)
        file_path = str('/static/blog_images/'+filename)
        file.save(os.path.join('flaskblog\\static\\blog_images', filename))
        
        new_file = convertToBinaryData(file)
        print(new_file ,'/n')

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        print(file_path)
        post.blog_image=file_path
        
        db.session.commit()
        flash(f'Your Blog has been updated!', 'success')
        return redirect(url_for('posts.view_blog', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content


    return render_template('update_blog.html', title='Update Blog', form=form, post_id=post_id)



@posts.route("/blog/delete/<int:post_id>",methods=['POST'])
@login_required
def delete_blog(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Your Blog has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, UpdateUserForm
from flaskblog.users.utils import save_user_image, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=('GET', 'POST'))
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created successfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)



@users.route("/login", methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login unsuccessfully!', 'danger')
            return redirect(url_for('users.login'))
    return render_template('login.html', title='Login',form=form)



@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users.route("/account")
@login_required
def account():
    image_file = url_for('static', filename='profile_pics/default.jpg' )
    posts = Post.query.all()
    posts_list = []
    for post in posts:
        if current_user.name == post.author.name:
            posts_list.append(post)

    print(len(posts_list))
    return render_template('account.html', title='Account', image_file=image_file, posts_list=posts_list)



@users.route("/updateaccount",methods=('GET', 'POST'))
@login_required
def updateaccount():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.user_image.data:
            image_file = save_user_image(form.user_image.data)
            current_user.user_image = image_file
        current_user.name = form.name.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f'Your account has been updated!', 'success')
        return redirect(url_for('users.updateaccount'))
    
    elif request.method=='GET':
        form.name.data = current_user.name
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/default.jpg' )
    return render_template('updateaccount.html', title='Update Account', image_file=image_file, form=form)



@users.route("/user/profile/<name>")
def user_profile(name):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(name=name).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
    image_file = url_for('static', filename='profile_pics/default.jpg' )  #This is a static image for testing
    return render_template('user_profile.html', user=user, posts=posts, image_file=image_file)



@users.route("/request_reset",methods=('GET', 'POST'))
def request_reset():
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset yor password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', form=form)



@users.route("/request_reset/<token>",methods=('GET', 'POST'))
def reset_password(token):

    user = User.verify_reset_token(token)

    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))

    

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()

        flash(f'Your Password has been updated successfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block css %}
<link href="{{ url_for('static', filename='css/about.css') }}" rel="stylesheet">
  
{% endblock css %}
{% block body %}


<section>
    <h1>Welcome to my website !! </h1><br>
    <p style="bottom:20px; position: absolute;">Scroll Down &#8595;</p>
  </section>

  
  <section>
    <div class="container reveal fade-left">

      <div class="text-container">
        <div class="text-box" id="name">
          <h1 style="font-family: 'Times New Roman', Times, serif;font-size: 5.7rem; margin-bottom:40px;">Sourabh Bera</h1> 
          
        </div>
        <div class="text-box">
            <img src="{{ profle_pic }}" class="img-fluid" alt="..." width="30%" style="float: right; border-radius:15px; margin-right: 75px;">
        </div>

      </div>
    </div>
  </section>
  
  <section>
    <div class="container reveal fade-right">
      <h2>Details</h2>
      <div class="text-container">
        <div class="text-box" style="width:1150px; margin-left:85px;">
          <p>
            Hello, my name is Sourabh Bera I am currently a third-year student pursuing a Bachelor of Engineering 
            in Information Technology from Terna Engineering College, Navi-Mumbai. <br><br>
            As an aspiring IT professional, Everyday I am even more excited to delve deeper into advanced IT topics than yesterday, such as artificial intelligence, cloud computing, and cybersecurity. 
            I am keen to explore how these emerging technologies can revolutionize industries and trying to gain knowledge about them and how to use them in for my benifits.<br><br>
            I have actively participated in group projects and collaboration, where I have honed my communication and problem-solving skills while working alongside diverse teams. These experiences have not only broadened my perspective 
            but also helped me to learn someting new everyday.
          </p>
        </div>     
      </div>
    </div>
  </section>

  <section>
    <div class="container reveal fade-bottom" style="color: white;">
      <h2 style="position:inherit; top:-100px;">contact details</h2>
      <div class="text-container" style="justify-content: center; position:inherit; top:-70px;">
        <div class="text-box" style="padding-right: 140px;">
            <h3 style="margin-bottom: 40px;">Personal</h3>
            <p>
                Email Id: &nbsp;sourabhbera86@gmail.com <br>
                Phone No: &nbsp;+91 99879322745
            </p>

        </div>

        <div class="text-box">
    
            <h3 style="margin-bottom: 40px;">Social</h3>
            <p>
                Linkedin:&nbsp; <a href="https://www.linkedin.com/in/sourabh-bera/" target="_blank">sourabh-bera</a> <br>
                GitHub:&nbsp; <a href="https://github.com/SourabhBera" target="_blank">SourabhBera</a>
            </p>
        </div>

        
      </div>
    </div>
  </section> 

<script>
    function reveal() {
        var reveals = document.querySelectorAll(".reveal");
      
        for (var i = 0; i < reveals.length; i++) {
          var windowHeight = window.innerHeight;
          var elementTop = reveals[i].getBoundingClientRect().top;
          var elementVisible = 150;
      
          if (elementTop < windowHeight - elementVisible) {
            reveals[i].classList.add("active");
          } else {
            reveals[i].classList.remove("active");
          }
        }
      }
      
      window.addEventListener("scroll", reveal);
    

</script>

{% endblock body %}

flaskblog/templates/account.html
{% extends "layout.html" %}

{% block css %}
<link href="{{ url_for('static', filename='css/account.css') }}" rel="stylesheet">
{% endblock css %}

{% block body %}
<div class="container"> 
    <section>
        <div class="main-container" id="main-contanier">
            <div class="container-media">
                <img src="{{ image_file }}" class="rounded float-start img-fluid" id="profile-img" alt="profile picture" >
                <div>
                    <h1 class="headname" > Hello ! <br>{{ current_user.name}}</h1>
                </div>
            </div>
        </div>
    </section>
    <div class="details-container" >
        <table class="styled-table">
            <thead>
                <tr>
                    <th style="padding-left: 40px; padding-right:40px;">Sr. No.</th>
                    <th style="padding-left: 40px; padding-right:40px;">Blog Title</th>
                    <th style="padding-left: 40px; padding-right:40px;">Date Posted</th>
                    <!-- <th style="padding-left: 40px; padding-right:40px;">Total Views</th> -->
                    <th style="padding-left: 50px; padding-right:50px;">Update / Delete</th>
                </tr>
            </thead>


            <tbody>              
                {% for post in posts_list %}              
                    {% if current_user.name == post.author.name %} 
                       
                        <tr>
                            <td style="padding-left: 40px; padding-right:40px;">{{ loop.index }}</td>
                            <td style="padding-left: 30px; padding-right:30px; "><a href="{{ url_for('posts.view_blog', post_id=post.id)}}"  class="blogname">{{ post.title }} </a></td>
                            <td style="padding-left: 40px; padding-right:40px;">{{ post.date_posted.strftime('%d-%m-%y') }}</td>
                            <!-- <td style="padding-left: 40px; padding-right:40px;">#</td> -->
                            <td style="padding-left: 15px; padding-right:15px;">
                                <a href="{{ url_for('posts.update_blog', post_id=post.id)}}" class="btn btn-dark btn-sm " style="margin-right:15px;">Update</a>
                                <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>

                                <!-- Modal -->
                                <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <form action="{{ url_for('posts.delete_blog', post_id=post.id )}}" method="POST">
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        </form>
                                        </div>
                                    </div>
                                    </div>
                                </div>

                            </td>
                        </tr>
                    
                    {% endif %}       
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
{% endblock body %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block body %}

<div class="home-main" >
    <h1>Bloggers!</h1>
    <p class="caption">Get Inspired, Get Motivated, Get Blogging with Us.</p>
    
    <div class="home-image">
        <img src="{{ vector3 }}" alt="" class="vector-img">
    </div>
</div> 




<div class="container" style="margin-top: 120px; margin-bottom:100px;">
  <h1 class="latestblogs"> Latest Blogs </h1>
    <div class="row" style="margin-left: 35px;">
        {% for post in posts.items %}
        <div class="card" style="width: 21rem;">
            <img src="{{post.blog_image}}" class="card-img-top" alt="..." width="310px" height="200px">
            <div class="card-body">
                <h5 class="card-title" style="margin-bottom: 15px;">{{ post.title }}</h5>
                <p style="padding-bottom: 45px; font-size:15px;">By <a href="{{ url_for('users.user_profile', name=post.author.name) }}">{{ post.author.name }}</a>,   {{ post.date_posted.strftime('%d-%m-%y') }}</p>
                <a href="{{ url_for('posts.view_blog', post_id=post.id)}}" class="btn btn-primary" style="bottom: 20px; position: absolute;">View</a>
            </div>
        </div>
        {% endfor %}

        <nav aria-label="Page navigation example" style="margin-top: 80px;">
            <ul class="pagination justify-content-center">
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              {% for page_num in posts.iter_pages(left_edge=1, right_edge=1) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                    <li class="page-item "><a class="page-link" id="selected-page" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% else %}
                    <li class="page-item "><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                ...
                {% endif %}
              {% endfor %}
              
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>  

    </div>
</div>
{% endblock body %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Latest compiled and minified CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="{{ url_for('static', filename='css/layout.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/register.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/home.css') }}" rel="stylesheet">
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


  {% block css %}
    
  {% endblock css %}


  <!-- Latest compiled JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>


  <!-- Title -->
  {% if title %}
  <title>Flask Blog - {{ title }}</title>
  {% else %}
  <title>Flask Blog</title>
  {% endif %}
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light" style="margin-bottom: 25px;">
    <div class="container-fluid" style="padding-left: 23px;">

      <a class="navbar-brand" href="{{ url_for('main.home') }}">Bloggers! </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item " style="margin-left: 15px;">
            <a class="nav-link" href="{{ url_for('main.home')}}" >Home</a>
            <div class="underline"></div>
          </li>

          <li class="nav-item " style="margin-left: 10px;">
            <a class="nav-link" href="{{ url_for('main.about')}}">About</a>
            <div class="underline"></div>
          </li>

          {% if current_user.is_authenticated %}

          <li class="nav-item dropdown" style="margin-left: 10px;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Dashboard
            </a>
            <div class="underline"></div>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{ url_for('users.account')}}">Account</a>
              <li><a class="dropdown-item" href="{{ url_for('users.updateaccount')}}">Update Account Info</a>
              <li><a class="dropdown-item" href="{{ url_for('posts.new_blog_post')}}">Create New Blog</a>
              <li><a class="dropdown-item" href="{{ url_for('users.logout')}}">Logout</a>
            </ul>
          </li>


          {% else %}
          
          <li class="nav-item dropdown" style="margin-left: 10px;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Register/Login
            </a>
            <div class="underline"></div>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{ url_for('users.register')}}">Register</a></li>
              <li><a class="dropdown-item" href="{{ url_for('users.login')}}">Login</a></li>
            </ul>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="/search" method="post" style="right: -530px; position: relative;" >
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" style="width:280px;">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
    {% endfor %}
  {% endif %}
  {% endwith %}


  {% block body %}

  {% endblock %}


<script type="text/javascript">
  
  $('.nav-item').on('click', function() {
    $('.active-link').removeClass('active-link');
    $(this).addClass('active-link');
  });


  $(document).ready(function () {
  window.setTimeout(function() {
      $(".alert").fadeTo(1000, 0).slideUp(1000, function(){
          $(this).remove(); 
      });
  }, 5000);
  });

</script>



</body>

</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block body %}
<div class="registerbody">
    <div class="wrapper">
        <h2>Login</h2>
        <form action="/login" method="post">
            {{form.csrf_token }}
            
            <div class="input-box">
                {{form.email.label }}

                {% if form.email.errors %}
                    {{form.email(class='is-invalid')}}
                    <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                {% else %}
                    {{form.email}}
                {% endif %}
            </div>

            <div class="input-box">
                {{form.password.label }}

                {% if form.password.errors %}
                    {{form.password(class='is-invalid')}}
                    <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                {% else %}
                    {{form.password}}
                {% endif %}
            </div>
            <div class="text">
                <h3 style="text-align:left; font-size: 12.7px;">Forgot password? <a href="{{ url_for('users.request_reset') }}" style="color:#E74646">Reset now</a></h3>
            </div>

            <div class="input-box button" style=" margin-bottom:10px;">
                <input type="Submit" value="Login" style="margin-top: -10px;">
            </div>
            <div class="text">
                <h3>Don't have a account? <a href="{{url_for('users.register')}}">Register now</a></h3>
            </div>
        </form>
    </div>
</div>
{% endblock body %}

flaskblog/templates/new_blog_post.html
{% extends "layout.html" %}

{% block css %}
<link href="{{ url_for('static', filename='css/new_blog_post.css') }}" rel="stylesheet">
{% endblock css %}

{% block body %}

<div class="d-flex align-items-center justify-content-center">
    <div class="wrap">
        <h2 class="header">Create New Blog</h2>

        <form action="/new/blogpost" method="post" enctype="multipart/form-data">
            {{form.csrf_token }}

            <div class="mb-5">
                {{form.title.label(class="form-label") }}

                {% if form.title.errors %}
                {{form.title(class='is-invalid')}}
                <div class="invalid-feedback" style="font-size: 13px;">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span><br>
                    {% endfor %}
                </div><br><br>
                {% else %}
                {{form.title (class="form-control")}}
                {% endif %}

            </div>

            <div class="mb-5">
                {{form.content.label(class="form-label") }}

                {% if form.content.errors %}
                {{form.content(class='is-invalid')}}
                <div class="invalid-feedback" style="font-size: 13px;">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span><br>
                    {% endfor %}
                </div><br><br>
                {% else %}
                {{form.content (class="form-control2")}}
                {% endif %}
            </div>

            <div class="form-file">
                {{form.blog_image.label(class="form-label") }} <br>
                {{form.blog_image(class="form-control-file") }}

                {% if form.blog_image.errors %}
                        {% for error in form.blog_image.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                {% endif %}
            </div>

            <div class="input-box button" style="margin-top:17px; height: 50px;">
                <input type="Submit" value="Post New Blog">
            </div>

        </form>
    </div>
</div>

{% endblock body %}

flaskblog/templates/request_reset.html
{% extends "layout.html" %}
{% block body %}
<div class="registerbody">
    <div class="wrapper">
        <h2>Request Reset</h2>
        <form action="/request_reset" method="post">
            {{form.csrf_token }}
            
            <div class="input-box">
                {{form.email.label }}

                {% if form.email.errors %}
                    {{form.email(class='is-invalid')}}
                    <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                {% else %}
                    {{form.email}}
                {% endif %}
            </div>

            <div class="input-box button" style=" margin-bottom:10px;">
                <input type="Submit" value="Reset" style="margin-top: -10px;">
            </div>
            
        </form>
    </div>
</div>
{% endblock body %}

flaskblog/templates/view_blog.html
{% extends 'layout.html' %}

{% block css %}
<link href="{{ url_for('static', filename='css/view_blog.css') }}" rel="stylesheet">
  
{% endblock css %}
{% block body %}

<div class="container">
    <section>
        <h1 class="blogheading">{{ post.title }}</h1>
        <span class="blogauthor"> Author: <a href="{{ url_for('users.user_profile', name=post.author.name) }}"> {{post.author.name}}</a> </span> <br>
        <span style="margin-left: 30px;">Posted on {{post.date_posted.strftime('%d-%m-%y') }}</span> <br>
        <div class="img-container" >
            <img src="{{ post.blog_image }}" width="780" height="470">
        </div>
        <div class="blogcontent" style="word-wrap: break-word;white-space: pre-wrap; display:flex;">{{ post.content }}</div>
    </section>

    {% if current_user.name == post.author.name %}
    <div class="delupdate">
        <a href="{{ url_for('posts.update_blog', post_id=post.id)}}" class="btn btn-dark btn " style="margin-right: 20px; margin-left: 30px;">Update</a>
        <button type="button" class="btn btn-danger btn m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_blog', post_id=post.id )}}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>

    
{% endblock body %}